### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by gedankenstuecke** [mpdunne/orthofiller#2]
Hey there,
I just tried to install `orthofiller` and it seems the README does not fully capture the dependencies or the whole setup procedure at this point: In order to get it run you don't only need to have the `OrthoFinder` location in your `$PATH` but actually you need to have all the uncompiled source of `OrthoFinder` in the folder that you use for starting `orthofiller`. 

Otherwise it would constantly crash because it was unable to find the `mcl` scripts as well as the `OrthoFinder.py` itself. I solved it by [downloading the source version](https://github.com/davidemms/OrthoFinder/releases/tag/1.1.2) and then putting `OrthoFinder.py` plus the complete `scripts` folder into the working directory from where i started `orthofiller`. 

Hope that is of some help! 

Cheers,
Bastian

**Comment by mpdunne** [comment]
HI Bastian,

Thanks for the info! I'm in the process of refactoring some of the code to remove some of these types of dependencies, and it should be more straightforward to run in a coming update.

All the best,

Michael

**Comment by gedankenstuecke** [comment]
Hi Michael,
thanks so much, really looking forward to see those changes! Also had a couple of other things I noticed, would also be happy to discuss those via email if you'd prefer (bgreshake@gmail.com)!

Cheers,
Bastian
