### ISSUE TITLE
Augustus config path obtained from wrong variable

### ISSUE THREAD

**Issue by MatteoSchiavinato** [mpdunne/orthofiller#4]
Hi, I am trying to use OrthoFiller and I noticed that in the runOrthoFil.sh script the AUGUSTUS_CONFIG_PATH is assigned to a variable which is not actually declared before. 

**loc**_augustus=""         # path to augustus config directory
export AUGUSTUS_CONFIG_PATH=$**cfg**_augustus

**Comment by mpdunne** [comment]
Hi Matteo,

Good spot, this has been fixed.

Michael
